src/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
]

src/images/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.urls import reverse

User = get_user_model()


class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images_created')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='media/images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(User, related_name='images_liked', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Creates slug field for ImageModel from title field
        """
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', kwargs={
            'id': self.pk,
            'slug': self.slug
        })

src/images/forms.py
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django import forms
from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'png', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given url does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        """
        Downloads the image before saving given the url in the form
        """
        image = super().save(commit=False)
        image_url = self.cleaned_data.get('url')
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'

        # download the image from the given url
        response = request.urlopen(image_url)
        # call File.save() method to save/update the file associated with
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()

        return image

src/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
from account.models import User
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def image_list(request):
    """
    Returns all the image list of every user
    """
    images = Image.objects.all()
    paginator = Paginator(images, per_page=6)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # return an empty page if ajax request
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', {
            'section': 'images',
            'images': images
        })
    return render(request, 'images/image/list.html', {
        'images': images,
        'section': 'images'
    })


@login_required
def image_create(request):
    """
    Manually creates images to bookmark
    """
    # TODO: Add image upload functionality to this view
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)    
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # assign current user to the image
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            # redirect to new created image detail page
            return redirect(new_item.get_absolute_url())
    else:
        # build the form with data provided by bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    
    return render(request, 'images/image/create.html', context={
        'section': 'images',
        'form': form
    })


@login_required
def image_detail(request, id: int, slug: str):
    # get the object
    image = get_object_or_404(Image, pk=id, slug=slug)
    return render(request, 'images/image/detail.html', {
        'image': image,
        'section': 'images',
        })


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({
        'status': 'error'
    })

src/images/templates/images/image/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}

<div class="card-border-light">
    <div class="card-header">
        <h5 class="text-primary">Bookmark an image</h5>
    </div>
    <div class="row">
        <div class="col-sm-5">
            <div class="card-border-light">
                <div class="card-body">
                    <img src="{{ request.GET.url }}" width=430 height=430 alt="Broken image">
                </div>
            </div>
        </div>
        <div class="col-sm-7">
            <div class="card-border-light">
                <div class="card-body">
                    <form method="POST">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <div class="float-right mx-2">
                            <a href="#" class="btn btn-warning">Cancel</a>
                            <input type="submit" href="{% url 'images:create' %}" class="btn btn-primary" value="Bookmark It"></input>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

src/images/templates/images/image/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Image Detail {% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-5">
        <div class="card">
            <div class="card-body">
                <a href="{{ image.image.url }}">
                    <img src="{% thumbnail image.image 350x0 quality=100 %}" alt="">
                </a>                
            </div>
        </div>
    </div>    
    <div class="col-md-7 card">
        <div class="card-header">
            <h4 class="text-primary"> {{ image.title }} </h4>
            {% with total_likes=image.users_like.count users_like=image.users_like.all %}
            <div class="d-flex justify-content-between">
                <!-- <span id="totalLikes" class="badge badge-pill badge-warning">
                    {{ total_likes }} like{{ total_likes|pluralize }}
                </span> -->
                <button type="button" class="btn btn-warning rounded-pill">
                    Total Likes <span id="totalLikes" class="badge badge-light">{{ total_likes }}</span>
                </button>
                <a href="#" id="likeBtn" data-id={{ image.id }}
                            data-action="{% if request.user in users_like %}un{% endif %}like"
                            class="btn btn-danger rounded-pill">
                            {% if request.user in users_like %}
                            Unlike
                            {% else %}
                            Like
                            {% endif %}
                </a>
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                {{ image.description|linebreaks }}
            </h5>
            {% for user in users_like %}
            <!-- <img src="{{ user.profile.photo.url }}" alt=""> -->
            <p>{{ user.first_name }}</p>
            {% empty %}
                Nobody likes this image yet.
            {% endfor %}
            {% endwith %}
        </div>
    </div>
</div>    
{% endblock content %}

{% block domready %}
    $('a#likeBtn').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if(data['status'] == 'ok'){
                    var previousAction = $('a#likeBtn').data('action');
                    // toggle data-action
                    $('a#likeBtn').data('action', previousAction == 'like' ? 'unlike' : 'like');

                    // toggle the link text 
                    $('a#likeBtn').text(previousAction == 'like' ? 'Unlike': 'Like');

                    // Update the total likes 
                    var previousLikes = parseInt($('span#totalLikes').text());
                    $('span#totalLikes').text(previousAction == 'like' ? previousLikes + 1 : previousLikes - 1);
                }
            }
        );
    });
{% endblock %}

src/images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %} Images {% endblock title %}

{% block content %}
<div class="card-deck ml-3" id="image-list">
    {% include "images/image/list_ajax.html" %}
</div>
{% endblock %}

{% block domready %}
    var page = 1;
    var emptyPage = false;
    var blockRequest = false;

    <!-- Scroll Down Event -->
    $(window).scroll(function(){
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).scrollTop() > margin && emptyPage == false && blockRequest == false) {
            blockRequest = true;
            page += 1;
            $.get('?page=' + page, function(data){
                if (data == ''){
                    emptyPage = true;
                }
                else {
                    blockRequest = false;
                    $('#image-list').append(data);
                }
            });
        }
    });

    <!-- Key Down event -->
    $(window).keydown(function(){
        console.log("Key down event triggered")
        var margin = $(document).height() - $(window).height() - 200;
        if ($(window).keyup() > margin && emptyPage == false && blockRequest == false) {
            blockRequest = true;
            page += 1;
            $.get('?page=' + page, function(data){
                if (data == ''){
                    emptyPage = true;
                }
                else {
                    blockRequest = false;
                    $('#image-list').append(data);
                }
            });
        }
    });

    <!-- Like event -->
    $('a#likeBtn').click(function(e){
        var likeBtn = $(this)
        var id = likeBtn.data('id');
        var previousAction = likeBtn.data('action');
        console.log("id: " + id);
        console.log("action: " + previousAction);
        
        e.preventDefault();
        
        $.post('{% url "images:like" %}',
            {
                id: id,
                action: previousAction
            },
            function(data){
                var likeIcon = $('i#likeIcon' + id );
                if(data['status'] == 'ok'){
                    // toggle data-action
                    likeBtn.data('action', previousAction == 'like' ? 'unlike' : 'like');

                    // toggle the inner HTML
                    if (previousAction == 'like') {
                        likeIcon.removeClass('bi-heart').addClass('bi-heart-fill');
                        
                    } else {
                        likeIcon.removeClass('bi-heart-fill').addClass('bi-heart');
                    } 
                }
            }
        );
    });
{% endblock %}

src/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
<div class="card my-3" style="min-width: 300px; max-width: 300px;">
    <a href="{{ image.get_absolute_url }}">
        <img class="card-img-top" width="300" height="280" src="{{ image.url }}" alt="Card image cap">
    </a>
    <div class="card-body">
        <h5 class="card-title">{{ image.title }}</h5>
        <p class="card-text">{{ image.description }}</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
    <div class="card-footer">
        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <a class="btn btn-warning" href="{{ image.get_absolute_url }}"><i class="bi bi-eyeglasses"></i> Details</a>
        <a href="#" class="btn btn-danger" id="likeBtn" 
                data-action="{% if request.user in users_like %}un{% endif %}like"
                data-id={{ image.id }}>
            {% if request.user in users_like %}
            <i id="likeIcon{{image.id}}" class="bi bi-heart-fill"></i>
            {% else %}
            <i id="likeIcon{{image.id}}" class="bi bi-heart"></i>
            {% endif %}
        </a>
        {% endwith %}
        <!-- <a class="btn btn-danger" href="#"> <i class="bi bi-heart"></i> </a>
        <a class="btn btn-danger" href="#"> <i class="bi bi-heart-fill"></i> </a> -->
    </div>
</div>
{% endfor %}

<!-- <div id="image-list">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}" alt="">
        </a>
    </a>
    <div>
        <a href="{{ image.get_absolute_url }}">
            {{ image.title }}
        </a>
    </div>
</div> -->